/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  henrique.ostermann
 * Created: 15/12/2016
 */
-- -- TABELA USUARIO
-- INSERT INTO USUARIO (ID_USUARIO, EMAIL_USUARIO, SENHA_USUARIO, NOME_USUARIO)  VALUES (SEQ_USUARIO.nextval, 'henrique.ostermann@cwi.com.br', 'henriqueostermann', 'Henrique');
-- INSERT INTO USUARIO (ID_USUARIO, EMAIL_USUARIO, SENHA_USUARIO, NOME_USUARIO)  VALUES (SEQ_USUARIO.nextval, 'felipe.souza@cwi.com.br', 'felipesouza', 'Felipe');
-- INSERT INTO USUARIO (ID_USUARIO, EMAIL_USUARIO, SENHA_USUARIO, NOME_USUARIO)  VALUES (SEQ_USUARIO.nextval, 'william.cardozo@cwi.com.br', 'williamcardozo', 'William');
-- -- INSERT INTO USUARIO (ID_USUARIO, EMAIL_USUARIO, SENHA_USUARIO, NOME_USUARIO)  VALUES (SEQ_SALA.nextval, 'henrique.ostermann@cwi.com.br', 'henriqueostermann', 'Henrique');
-- 
-- --TABELA EQUIPAMENTOS   
-- INSERT INTO EQUIPAMENTO (ID_EQUIPAMENTO, NOME_EQUIPAMENTO)  VALUES (SEQ_EQUIPAMENTO.nextval, 'TELEVISAO');
-- INSERT INTO EQUIPAMENTO (ID_EQUIPAMENTO, NOME_EQUIPAMENTO)  VALUES (SEQ_EQUIPAMENTO.nextval, 'TELEFONE');
-- INSERT INTO EQUIPAMENTO (ID_EQUIPAMENTO, NOME_EQUIPAMENTO)  VALUES (SEQ_EQUIPAMENTO.nextval, 'COMPUTADOR');
-- 
-- -- TABELA SALA_EQUIPAMENTO
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (1, 1);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (1, 2);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (1, 3);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (2, 1);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (2, 2);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (3, 1);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (3, 3);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (3, 3);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (3, 3);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (3, 3);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (4, 1);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (5, 2);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (6, 3);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (7, 2);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (8, 3);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (8, 3);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (8, 1);
-- INSERT INTO SALA_EQUIPAMENTO (SALA_ID_SALA, EQUIPAMENTO_ID_EQUIPAMENTO)  VALUES (9, 3);
-- 
-- 
-- 
-- 
-- -- TABELA SALA
-- INSERT INTO SALA (ID_SALA, NOME_SALA, CAPACIDADE_SALA, EQUIPAMENTO_SALA)  VALUES (SEQ_SALA.nextval, '3.1', 10, );
-- INSERT INTO SALA (ID_SALA, NOME_SALA, CAPACIDADE_SALA, EQUIPAMENTO_SALA)  VALUES (SEQ_SALA.nextval, '3.2', 10, );
-- INSERT INTO SALA (ID_SALA, NOME_SALA, CAPACIDADE_SALA, EQUIPAMENTO_SALA)  VALUES (SEQ_SALA.nextval, '4.1', 10, );
-- INSERT INTO SALA (ID_SALA, NOME_SALA, CAPACIDADE_SALA, EQUIPAMENTO_SALA)  VALUES (SEQ_SALA.nextval, '4.2', 10, );
-- INSERT INTO SALA (ID_SALA, NOME_SALA, CAPACIDADE_SALA, EQUIPAMENTO_SALA)  VALUES (SEQ_SALA.nextval, '4.3', 10, );
-- INSERT INTO SALA (ID_SALA, NOME_SALA, CAPACIDADE_SALA, EQUIPAMENTO_SALA)  VALUES (SEQ_SALA.nextval, '4.4', 10, );
-- INSERT INTO SALA (ID_SALA, NOME_SALA, CAPACIDADE_SALA, EQUIPAMENTO_SALA)  VALUES (SEQ_SALA.nextval, '5.1', 10, );
-- INSERT INTO SALA (ID_SALA, NOME_SALA, CAPACIDADE_SALA, EQUIPAMENTO_SALA)  VALUES (SEQ_SALA.nextval, '5.2', 10, );
-- INSERT INTO SALA (ID_SALA, NOME_SALA, CAPACIDADE_SALA, EQUIPAMENTO_SALA)  VALUES (SEQ_SALA.nextval, 'Auditorio', 30, );
-- 
-- 
-- 
